/*
 * modules.conf
 *
 * This configuration file specifies which modules to load for the IRC server.
 *
 * Syntax:
 * loadmodule "module_name" [ : attribute1 [, attribute2, ...] ];
 *
 * - "module_name" : The name of the module file to load.
 * - "core"           : Essential for server functionality; can be reloaded but not unloaded.
 * - "resident"       : Cannot be unloaded or reloaded once loaded.
 *
 * Note: If no attributes (core, resident) are specified, the module is considered
 *       a regular, non-essential module that can be loaded and unloaded as needed.
 */

/*
 * module_base_path: Specifies the base directory for module files. This path can be
 * either an absolute path or a path relative to the current working directory.
 */
module_base_path = "./lib/ircd-hybrid/modules";

loadmodule "cap_account_notify";
loadmodule "cap_away_notify";
loadmodule "cap_cap_notify";
loadmodule "cap_chghost";
loadmodule "cap_extended_join";
loadmodule "cap_invite_notify";
loadmodule "cap_multi_prefix";
loadmodule "cap_standard_replies";
loadmodule "cap_userhost_in_names";
loadmodule "umode_admin";
loadmodule "umode_bot";
loadmodule "umode_callerid";
loadmodule "umode_cloak";
loadmodule "umode_connect";
loadmodule "umode_deaf";
loadmodule "umode_expiration";
loadmodule "umode_external";
loadmodule "umode_farconnect";
loadmodule "umode_flood";
loadmodule "umode_hidden";
loadmodule "umode_hidechans";
loadmodule "umode_hideidle";
loadmodule "umode_invisible";
loadmodule "umode_locops";
loadmodule "umode_nickchange";
loadmodule "umode_oper";
loadmodule "umode_registered";
loadmodule "umode_regonly";
loadmodule "umode_reject";
loadmodule "umode_secure";
loadmodule "umode_secureonly";
loadmodule "umode_servnotice";
loadmodule "umode_skill";
loadmodule "umode_softcallerid";
loadmodule "umode_spy";
loadmodule "umode_webirc";
loadmodule "m_accept";
loadmodule "m_admin";
loadmodule "m_away";
loadmodule "m_bmask" : core;
loadmodule "m_cap";
loadmodule "m_capab";
loadmodule "m_certfp";
loadmodule "m_close";
loadmodule "m_connect";
loadmodule "m_die" : core;
loadmodule "m_dline";
loadmodule "m_encap";
loadmodule "m_eob";
loadmodule "m_error" : core;
loadmodule "m_etrace";
loadmodule "m_globops";
loadmodule "m_help";
loadmodule "m_info";
loadmodule "m_invite";
loadmodule "m_ison";
loadmodule "m_join" : core;
loadmodule "m_kick" : core;
loadmodule "m_kill" : core;
loadmodule "m_kline";
loadmodule "m_knock";
loadmodule "m_links";
loadmodule "m_list";
loadmodule "m_locops";
loadmodule "m_lusers";
loadmodule "m_map";
loadmodule "m_message" : core;
loadmodule "m_metadata";
loadmodule "m_mlock" : core;
loadmodule "m_mode" : core;
loadmodule "m_module" : resident;
loadmodule "m_monitor";
loadmodule "m_motd";
loadmodule "m_names";
loadmodule "m_nick" : core;
loadmodule "m_oper";
# loadmodule "m_opme";
loadmodule "m_part" : core;
loadmodule "m_pass";
loadmodule "m_ping";
loadmodule "m_pong";
loadmodule "m_post";
loadmodule "m_quit" : core;
loadmodule "m_rehash";
loadmodule "m_restart";
loadmodule "m_resv";
loadmodule "m_resync";
loadmodule "m_server" : core;
loadmodule "m_set";
loadmodule "m_sjoin" : core;
loadmodule "m_squit" : core;
loadmodule "m_stats";
loadmodule "m_svinfo";
loadmodule "m_svsaccount";
loadmodule "m_svshost";
loadmodule "m_svsjoin";
loadmodule "m_svskill";
loadmodule "m_svsmode";
loadmodule "m_svsnick";
loadmodule "m_svspart";
loadmodule "m_svstag";
loadmodule "m_tburst";
loadmodule "m_time";
loadmodule "m_tmode" : core;
loadmodule "m_topic";
loadmodule "m_trace";
loadmodule "m_undline";
loadmodule "m_unkline";
loadmodule "m_unresv";
loadmodule "m_unxline";
loadmodule "m_user";
loadmodule "m_userhost";
loadmodule "m_version";
loadmodule "m_webirc";
loadmodule "m_who";
loadmodule "m_whois";
loadmodule "m_whowas";
loadmodule "m_xline";
